'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';

export default function AdminDashboard() {
  const { user } = useAuth();
  const [dateRange, setDateRange] = useState('7d');
  const [isLoading, setIsLoading] = useState(false);

  // Mock Data State
  const [stats, setStats] = useState({
    revenue: { value: 124500, label: 'Total Revenue', trend: '+12.5%' },
    orders: { value: 452, label: 'Total Orders', trend: '+5.2%' },
    visitors: { value: 14205, label: 'Unique Visitors', trend: '-2.4%' },
    avgOrder: { value: 1850, label: 'Avg. Order Value', trend: '+8.1%' }
  });

  // Simulating data fetch based on date filter (Non-blocking)
  useEffect(() => {
    const timer = setTimeout(() => {
      // Just mock date change logic without UI blocking
      setStats(prev => ({
        ...prev,
        revenue: { ...prev.revenue, value: Math.floor(124500 * (0.9 + Math.random() * 0.2)) },
      }));
    }, 0);
    return () => clearTimeout(timer);
  }, [dateRange]);

  const recentOrders = [
    { id: '#ORD-7741', item: 'Kanchipuram Silk Saree', customer: 'Rahul K.', amount: '₹ 8,499', status: 'Pending', time: '2 min ago' },
    { id: '#ORD-7740', item: 'Cotton Mundu Set', customer: 'Sarah J.', amount: '₹ 899', status: 'Shipped', time: '2 hours ago' },
    { id: '#ORD-7739', item: 'Kids Festival Wear', customer: 'Mohammed A.', amount: '₹ 1,299', status: 'Delivered', time: '5 hours ago' },
    { id: '#ORD-7738', item: 'Designer Churidar', customer: 'Priya S.', amount: '₹ 3,450', status: 'Processing', time: '1 day ago' },
  ];

  const topProducts = [
    { name: 'Banarasi Silk Saree', sales: 120, revenue: '₹ 2,40,000' },
    { name: 'Kerala Kasavu Mundu', sales: 85, revenue: '₹ 42,500' },
    { name: 'Designer Salwar', sales: 64, revenue: '₹ 98,200' },
    { name: 'Kids Frock (Red)', sales: 50, revenue: '₹ 22,500' },
  ];

  // Export Functionality
  const handleExport = () => {
    const printContent = `
      <html>
        <head>
          <title>Dashboard Report - ${new Date().toLocaleDateString()}</title>
          <style>
            body { font-family: sans-serif; padding: 20px; }
            h1 { color: #111; border-bottom: 2px solid #eee; padding-bottom: 15px; margin-bottom: 30px; }
            .metrics { display: flex; gap: 20px; margin-bottom: 40px; }
            .metric-box { border: 1px solid #ddd; padding: 15px; border-radius: 8px; flex: 1; text-align: center; }
            .metric-box h3 { margin: 10px 0 5px; font-size: 24px; color: #d32f2f; }
            .metric-box p { margin: 0; color: #666; font-size: 14px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { text-align: left; padding: 12px; border-bottom: 1px solid #eee; }
            th { background: #f9f9f9; color: #111; }
            .footer { margin-top: 50px; font-size: 12px; color: #999; text-align: center; }
          </style>
        </head>
        <body>
          <h1>Admin Dashboard Report</h1>
          <p><strong>Date:</strong> ${new Date().toLocaleString()}</p>
          <p><strong>Filter Range:</strong> ${dateRange.toUpperCase()}</p>
          
          <div class="metrics">
            <div class="metric-box">
              <p>${stats.revenue.label}</p>
              <h3>₹ ${stats.revenue.value.toLocaleString()}</h3>
              <small>${stats.revenue.trend}</small>
            </div>
            <div class="metric-box">
              <p>${stats.orders.label}</p>
              <h3>${stats.orders.value}</h3>
              <small>${stats.orders.trend}</small>
            </div>
            <div class="metric-box">
              <p>${stats.visitors.label}</p>
              <h3>${stats.visitors.value.toLocaleString()}</h3>
              <small>${stats.visitors.trend}</small>
            </div>
            <div class="metric-box">
              <p>${stats.avgOrder.label}</p>
              <h3>₹ ${stats.avgOrder.value.toLocaleString()}</h3>
              <small>${stats.avgOrder.trend}</small>
            </div>
          </div>

          <h2>Top Products Performance</h2>
          <table>
            <thead>
              <tr>
                <th>Product</th>
                <th>Sales Count</th>
                <th>Revenue Generated</th>
              </tr>
            </thead>
            <tbody>
              ${topProducts.map(p => `
                <tr>
                  <td>${p.name}</td>
                  <td>${p.sales}</td>
                  <td>${p.revenue}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>

          <div class="footer">
            Generated by Adavakkad Admin System
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '', 'width=800,height=800');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);
    }
  };

  return (
    <div className="dashboard-page">
      {/* Header */}
      <div className="page-header">
        <div>
           <h1 className="page-title">Dashboard Overview</h1>
           <p className="subtitle">Welcome back, {user?.name || 'Admin'}. Here&apos;s what&apos;s happening today.</p>
        </div>
        <div className="controls">
          <select value={dateRange} onChange={(e) => setDateRange(e.target.value)} className="date-select">
            <option value="today">Today</option>
            <option value="yesterday">Yesterday</option>
            <option value="7d">Last 7 Days</option>
            <option value="30d">Last 30 Days</option>
            <option value="year">This Year</option>
          </select>
          <button onClick={handleExport} className="primary-btn"><span className="material-symbols-outlined">download</span> Export PDF</button>
        </div>
      </div>

      {/* Metrics Row */}
      <div className={`metrics-grid ${isLoading ? 'loading' : ''}`}>
        <div className="metric-card">
          <div className="metric-header">
            <div className="icon-box green"><span className="material-symbols-outlined">payments</span></div>
            <span className={`trend ${stats.revenue.trend.includes('+') ? 'up' : 'down'}`}>{stats.revenue.trend}</span>
          </div>
          <h3>₹ {stats.revenue.value.toLocaleString()}</h3>
          <p>{stats.revenue.label}</p>
        </div>
        <div className="metric-card">
          <div className="metric-header">
            <div className="icon-box blue"><span className="material-symbols-outlined">shopping_bag</span></div>
            <span className={`trend ${stats.orders.trend.includes('+') ? 'up' : 'down'}`}>{stats.orders.trend}</span>
          </div>
          <h3>{stats.orders.value.toLocaleString()}</h3>
          <p>{stats.orders.label}</p>
        </div>
        <div className="metric-card">
          <div className="metric-header">
            <div className="icon-box orange"><span className="material-symbols-outlined">group</span></div>
            <span className={`trend ${stats.visitors.trend.includes('+') ? 'up' : 'down'}`}>{stats.visitors.trend}</span>
          </div>
          <h3>{stats.visitors.value.toLocaleString()}</h3>
          <p>{stats.visitors.label}</p>
        </div>
         <div className="metric-card">
          <div className="metric-header">
            <div className="icon-box purple"><span className="material-symbols-outlined">receipt_long</span></div>
            <span className={`trend ${stats.avgOrder.trend.includes('+') ? 'up' : 'down'}`}>{stats.avgOrder.trend}</span>
          </div>
          <h3>₹ {stats.avgOrder.value.toLocaleString()}</h3>
          <p>{stats.avgOrder.label}</p>
        </div>
      </div>

      {/* Main Content Grid */}
      <div className="content-grid">
        {/* Left Col: Sales Chart (Mock) & Top Products */}
        <div className="main-col">
          <div className="card chart-card">
            <div className="card-header">
              <h2>Revenue Analytics</h2>
              <button className="icon-btn"><span className="material-symbols-outlined">more_horiz</span></button>
            </div>
            <div className="chart-placeholder">
              {/* CSS Simple Bar Chart Mockup */}
              {[40, 65, 45, 80, 55, 90, 70, 85, 60, 75, 50, 95].map((h, i) => (
                <div key={i} className="bar-group">
                  <div className="bar" style={{ height: `${h}%` }}></div>
                  <span className="label">{i + 1}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="card">
            <div className="card-header">
              <h2>Top Selling Products</h2>
              <a href="#" className="link">View All</a>
            </div>
            <table className="simple-table">
              <thead>
                <tr>
                   <th>Product Name</th>
                   <th>Sales</th>
                   <th>Revenue</th>
                </tr>
              </thead>
              <tbody>
                {topProducts.map((p, i) => (
                  <tr key={i}>
                    <td>
                      <div className="product-cell">
                        <div className="p-img"></div>
                        <span>{p.name}</span>
                      </div>
                    </td>
                    <td>{p.sales}</td>
                    <td className="revenue">{p.revenue}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Right Col: Recent Activity & Quick Actions */}
        <div className="side-col">
          <div className="card">
            <div className="card-header">
              <h2>Recent Orders</h2>
            </div>
            <div className="activity-feed">
              {recentOrders.map((order, i) => (
                <div key={i} className="activity-item">
                  <div className={`status-dot ${order.status.toLowerCase()}`}></div>
                  <div className="activity-info">
                    <p className="main-text"><strong>{order.customer}</strong> ordered {order.item}</p>
                    <p className="sub-text">{order.id} • {order.amount}</p>
                  </div>
                  <span className="time">{order.time}</span>
                </div>
              ))}
            </div>
             <button className="view-all-btn">View All Orders</button>
          </div>

          <div className="card quick-actions">
             <h2>Quick Actions</h2>
             <div className="action-grid">
               <Link href="/admin/products" className="action-btn-link"><span className="material-symbols-outlined">add_box</span> Add Product</Link>
               <Link href="/admin/users" className="action-btn-link"><span className="material-symbols-outlined">person_add</span> Add User</Link>
               <Link href="/admin/invoices" className="action-btn-link"><span className="material-symbols-outlined">post_add</span> Create Invoice</Link>
               <Link href="/admin/settings" className="action-btn-link"><span className="material-symbols-outlined">settings</span> Settings</Link>
             </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .dashboard-page { padding-bottom: 2rem; }
        
        .page-header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 2rem; flex-wrap: wrap; gap: 1rem; }
        .page-title { font-family: var(--font-playfair); font-size: 2rem; color: #1a1a1a; margin: 0; }
        .subtitle { color: #666; margin: 0.5rem 0 0 0; }
        
        .controls { display: flex; gap: 1rem; }
        .date-select { padding: 0.6rem 1rem; border: 1px solid #ddd; border-radius: 8px; background: white; font-family: var(--font-outfit); cursor: pointer; outline: none; }
        .primary-btn { background: #1a1a1a; color: white; border: none; padding: 0.6rem 1.2rem; border-radius: 8px; display: flex; align-items: center; gap: 0.5rem; font-weight: 500; cursor: pointer; }
        
        /* Metrics */
        .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1.5rem; margin-bottom: 2rem; transition: opacity 0.3s; }
        .metrics-grid.loading { opacity: 0.5; pointer-events: none; }
        
        .metric-card { background: white; padding: 1.5rem; border-radius: 12px; box-shadow: 0 4px 6px rgba(0,0,0,0.02); transition: transform 0.2s; }
        .metric-card:hover { transform: translateY(-3px); box-shadow: 0 10px 15px rgba(0,0,0,0.05); }
        
        .metric-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1rem; }
        .icon-box { width: 48px; height: 48px; border-radius: 10px; display: flex; align-items: center; justify-content: center; }
        .icon-box.green { background: #ecfdf5; color: #10b981; }
        .icon-box.blue { background: #eff6ff; color: #3b82f6; }
        .icon-box.orange { background: #fff7ed; color: #f97316; }
        .icon-box.purple { background: #f3e8ff; color: #a855f7; }
        
        .trend { font-size: 0.8rem; font-weight: 600; padding: 0.2rem 0.5rem; border-radius: 12px; }
        .trend.up { background: #ecfdf5; color: #10b981; }
        .trend.down { background: #fef2f2; color: #ef4444; }
        
        .metric-card h3 { font-size: 1.8rem; margin: 0; color: #1a1a1a; letter-spacing: -0.5px; }
        .metric-card p { color: #888; margin: 0.2rem 0 0 0; font-size: 0.9rem; }

        /* Content Layout */
        .content-grid { display: grid; grid-template-columns: 2fr 1fr; gap: 1.5rem; }
        @media (max-width: 1024px) { .content-grid { grid-template-columns: 1fr; } }
        
        .main-col { display: flex; flex-direction: column; gap: 1.5rem; }
        .side-col { display: flex; flex-direction: column; gap: 1.5rem; }
        
        .card { background: white; border-radius: 12px; padding: 1.5rem; box-shadow: 0 2px 4px rgba(0,0,0,0.02); }
        .card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem; }
        .card-header h2 { font-size: 1.1rem; margin: 0; color: #1a1a1a; font-weight: 600; }
        .link { color: #d32f2f; font-size: 0.9rem; text-decoration: none; font-weight: 500; }
        .icon-btn { border: none; background: none; color: #999; cursor: pointer; }

        /* Chart Mock */
        .chart-placeholder { height: 250px; display: flex; align-items: flex-end; justify-content: space-between; padding-top: 1rem; }
        .bar-group { display: flex; flex-direction: column; align-items: center; gap: 0.5rem; height: 100%; justify-content: flex-end; width: 6%; }
        .bar { width: 100%; background: #d32f2f; border-radius: 4px 4px 0 0; opacity: 0.8; transition: height 0.5s ease; }
        .bar:hover { opacity: 1; }
        .label { font-size: 0.75rem; color: #999; }
        
        /* Table */
        .simple-table { width: 100%; border-collapse: collapse; }
        .simple-table th { text-align: left; color: #888; font-weight: 500; font-size: 0.85rem; padding-bottom: 1rem; border-bottom: 1px solid #eee; }
        .simple-table td { padding: 1rem 0; border-bottom: 1px solid #f9f9f9; font-size: 0.95rem; }
        .simple-table tr:last-child td { border-bottom: none; }
        
        .product-cell { display: flex; align-items: center; gap: 0.8rem; }
        .p-img { width: 32px; height: 32px; background: #f0f0f0; border-radius: 4px; }
        .revenue { font-weight: 600; color: #1a1a1a; }

        /* Activity Feed */
        .activity-feed { display: flex; flex-direction: column; gap: 1.2rem; }
        .activity-item { display: flex; align-items: flex-start; gap: 1rem; }
        .status-dot { width: 10px; height: 10px; border-radius: 50%; margin-top: 6px; flex-shrink: 0; }
        .status-dot.pending { background: #f59e0b; }
        .status-dot.shipped { background: #3b82f6; }
        .status-dot.delivered { background: #10b981; }
        .status-dot.processing { background: #8b5cf6; }
        
        .activity-info { flex: 1; }
        .main-text { margin: 0; font-size: 0.9rem; color: #333; line-height: 1.4; }
        .sub-text { margin: 0.2rem 0 0 0; font-size: 0.8rem; color: #888; }
        .time { font-size: 0.75rem; color: #aaa; white-space: nowrap; }
        
        .view-all-btn { width: 100%; margin-top: 1.5rem; padding: 0.8rem; border: 1px solid #eee; background: white; border-radius: 8px; color: #666; font-weight: 500; cursor: pointer; transition: all 0.2s; }
        .view-all-btn:hover { background: #f9f9f9; color: #333; }

        /* Quick Actions */
        .quick-actions { background: linear-gradient(135deg, #1a1a1a 0%, #333 100%); color: white; }
        .quick-actions h2 { color: white; margin-bottom: 1.5rem; }
        .action-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
        .action-btn-link { 
          border: none; 
          background: rgba(255,255,255,0.1); 
          color: white; 
          padding: 1rem; 
          border-radius: 8px; 
          display: flex; 
          flex-direction: column; 
          align-items: center; 
          gap: 0.5rem; 
          cursor: pointer; 
          transition: background 0.2s; 
          font-size: 0.9rem;
          text-decoration: none;
        }
        .action-btn-link:hover { background: rgba(255,255,255,0.2); }
        .action-btn-link span { font-size: 1.5rem; color: #ef5350; }
      `}</style>
    </div>
  );
}
